# Generated by Django 4.2.24 on 2025-09-18 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=128, unique=True)),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('date_of_brith', models.DateField()),
                ('country_code', models.CharField(max_length=5)),
                ('mobile_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'students',
                'indexes': [models.Index(fields=['email_address'], name='students_email_a_41e386_idx')],
            },
        ),
    ]
