# Generated by Django 4.2.24 on 2025-09-18 14:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exam_exam_timer'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done')], default='pending', max_length=20)),
                ('exam_result', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10, null=True)),
                ('max_exam_score', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exams', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exams', to='students.student')),
            ],
            options={
                'db_table': 'student_exams',
            },
        ),
        migrations.CreateModel(
            name='StudentExamResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='exams.questionanswer')),
                ('exam_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='exams.examquestion')),
                ('student_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.studentexam')),
            ],
            options={
                'db_table': 'student_exam_results',
                'indexes': [models.Index(fields=['student_exam'], name='student_exa_student_34788f_idx'), models.Index(fields=['exam_question'], name='student_exa_exam_qu_6f26f0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='studentexam',
            index=models.Index(fields=['student'], name='student_exa_student_763605_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexam',
            index=models.Index(fields=['exam'], name='student_exa_exam_id_8966aa_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexam',
            index=models.Index(fields=['status'], name='student_exa_status_b45bd3_idx'),
        ),
    ]
